from __future__ import annotations

import importlib.util
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


DATA_SOURCE_REGISTRY_VERSION = "0.1.0"
FEDERATED_SAFETY_DISCLOSURE = (
    "The live Ghost Beam demo uses the local synthetic JAX twin. External sources are "
    "read-only local importers, manifests, validation layers, provenance standards, or "
    "future connector stubs. No external source can write to hardware."
)


def backend_root() -> Path:
    return Path(__file__).resolve().parents[1]


def project_root() -> Path:
    return backend_root().parent


def public_datasets_root() -> Path:
    return backend_root() / "data" / "public_datasets"


def standards_root() -> Path:
    return backend_root() / "data" / "standards"


def boostr_manifest_path() -> Path:
    return public_datasets_root() / "boostr_manifest.json"


def fermilab_bpm_ipm_manifest_path() -> Path:
    return public_datasets_root() / "fermilab_bpm_ipm_manifest.json"


def materials_project_manifest_path() -> Path:
    return public_datasets_root() / "materials_project_context_manifest.json"


def openpmd_manifest_path() -> Path:
    return standards_root() / "openpmd_compatibility_manifest.json"


def workflowhub_manifest_path() -> Path:
    return standards_root() / "workflowhub_compatibility_manifest.json"


def synthetic_manifest_path() -> Path:
    return backend_root() / "data" / "synthetic_data_manifest.json"


def recorded_fixture_manifest_path() -> Path:
    return backend_root() / "data" / "recorded_runs" / "sample_recorded_drifted_twin_manifest.json"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


def load_json(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None
    return json.loads(path.read_text(encoding="utf-8"))


def frictionless_validation_report() -> dict[str, Any]:
    installed = importlib.util.find_spec("frictionless") is not None
    return {
        "standard_id": "frictionless",
        "name": "Frictionless Data validation",
        "status": "available" if installed else "not_installed",
        "validated_targets": [],
        "validation_errors": [],
        "note": (
            "Frictionless is installed and can validate tabular artifacts."
            if installed
            else "Frictionless is not installed; evidence bundle includes manifest-level validation status only."
        ),
    }


def _source(
    *,
    source_id: str,
    name: str,
    category: str,
    role: str,
    status: str,
    active: bool,
    writes_allowed: bool | str = False,
    local_only: bool = True,
    runtime_network_required: bool = False,
    doi: str | None = None,
    license: str | None = None,
    expected_format: str | None = None,
    description: str,
    safety_disclosure: str = FEDERATED_SAFETY_DISCLOSURE,
    manifest_path: Path | None = None,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "id": source_id,
        "name": name,
        "category": category,
        "role": role,
        "status": status,
        "active": active,
        "writes_allowed": writes_allowed,
        "local_only": local_only,
        "runtime_network_required": runtime_network_required,
        "description": description,
        "safety_disclosure": safety_disclosure,
    }
    if doi:
        payload["doi"] = doi
    if license:
        payload["license"] = license
    if expected_format:
        payload["expected_format"] = expected_format
    if manifest_path:
        payload["manifest_path"] = str(manifest_path.relative_to(project_root()))
        payload["manifest_available"] = manifest_path.exists()
    if metadata:
        payload["metadata"] = metadata
    return payload


def data_sources_list() -> list[dict[str, Any]]:
    frictionless_status = frictionless_validation_report()["status"]
    return [
        _source(
            source_id="synthetic_jax_twin",
            name="Synthetic JAX Digital Twin",
            category="core_demo",
            role="live demo, benchmark, virtual diagnostic training/testing",
            status="active",
            active=True,
            writes_allowed="simulated_only",
            expected_format="local synthetic scenario state",
            description="Local synthetic accelerator-control environment generated by Ghost Beam's JAX digital twin.",
            manifest_path=synthetic_manifest_path(),
        ),
        _source(
            source_id="synthetic_recorded_fixture",
            name="Synthetic Recorded Fixture",
            category="core_demo",
            role="deterministic recorded-run fixture and replay",
            status="active",
            active=True,
            writes_allowed=False,
            expected_format="local CSV/eLog fixture",
            description="Generated synthetic recorded run used for deterministic replay and offline gate evaluation.",
            manifest_path=recorded_fixture_manifest_path(),
        ),
        _source(
            source_id="boostr",
            name="BOOSTR: A Dataset for Accelerator Control Systems",
            category="public_dataset",
            role="public Fermilab Booster accelerator-control time-series analysis",
            status="adapter_ready",
            active=False,
            writes_allowed=False,
            doi="10.5281/zenodo.4382663",
            license="CC BY 4.0",
            expected_format="local CSV/parquet slice",
            description="Public accelerator-control dataset; local slice required; full dataset not bundled or auto-downloaded.",
            manifest_path=boostr_manifest_path(),
        ),
        _source(
            source_id="fermilab_bpm_ipm",
            name="Fermilab BPM/IPM Booster diagnostics dataset",
            category="public_dataset",
            role="public beam-position/profile diagnostics and emittance-comparison data",
            status="manifest_ready",
            active=False,
            writes_allowed=False,
            doi="10.5281/zenodo.17429707",
            expected_format="local CSV/parquet/raw data slice",
            description="Public diagnostics dataset manifest for future read-only beam-position/profile analysis.",
            manifest_path=fermilab_bpm_ipm_manifest_path(),
        ),
        _source(
            source_id="epics_archiver_stub",
            name="EPICS Archiver Appliance read-only connector stub",
            category="facility_connector",
            role="future archived PV retrieval",
            status="stub_disabled",
            active=False,
            writes_allowed=False,
            description="Disabled read-only interface shape for archived PV history; no live connection.",
        ),
        _source(
            source_id="pyarchappl_compatible",
            name="pyarchappl-compatible retrieval interface",
            category="facility_connector",
            role="future Python client compatibility for EPICS Archiver Appliance",
            status="stub_disabled",
            active=False,
            writes_allowed=False,
            description="Compatibility boundary for future pyarchappl-style archived PV retrieval; disabled in this MVP.",
        ),
        _source(
            source_id="openpmd",
            name="openPMD / openPMD-beamphysics compatibility",
            category="artifact_standard",
            role="future beam-physics artifact export/import",
            status="manifest_ready",
            active=False,
            writes_allowed=False,
            expected_format="manifest only",
            description="Compatibility manifest for future openPMD-style beam physics artifacts.",
            manifest_path=openpmd_manifest_path(),
        ),
        _source(
            source_id="frictionless",
            name="Frictionless Data validation",
            category="validation_standard",
            role="validate tabular event histories, benchmark tables, public-data import windows, and decision/export tables",
            status="active" if frictionless_status == "available" else "manifest_ready",
            active=frictionless_status == "available",
            writes_allowed=False,
            description="Validation layer for tabular Ghost Beam artifacts; dependency is optional.",
            metadata={"validation_status": frictionless_status},
        ),
        _source(
            source_id="ro_crate",
            name="RO-Crate evidence bundle",
            category="artifact_standard",
            role="package Decision Records, Diagnosis, Mission Reports, Benchmark Results, synthetic data manifests, and public source manifests",
            status="active",
            active=True,
            writes_allowed=False,
            expected_format="RO-Crate-style JSON-LD metadata",
            description="Local provenance packaging metadata included in Evidence Bundle exports.",
        ),
        _source(
            source_id="workflowhub",
            name="WorkflowHub / Workflow RO-Crate",
            category="future_extension",
            role="future workflow publication and provenance registry compatibility",
            status="manifest_ready",
            active=False,
            writes_allowed=False,
            description="Manifest-only compatibility marker for future WorkflowHub or Workflow RO-Crate publication.",
            manifest_path=workflowhub_manifest_path(),
        ),
        _source(
            source_id="materials_project",
            name="Materials Project",
            category="future_extension",
            role="future Genesis materials-candidate context; not used for accelerator control",
            status="manifest_ready",
            active=False,
            writes_allowed=False,
            description=(
                "Optional future materials-discovery context, separate from Ghost Beam's accelerator-control loop."
            ),
            manifest_path=materials_project_manifest_path(),
        ),
    ]


def data_sources_summary(sources: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    records = sources if sources is not None else data_sources_list()
    by_category: dict[str, int] = {}
    for source in records:
        category = str(source["category"])
        by_category[category] = by_category.get(category, 0) + 1
    return {
        "core_demo_sources": [source["id"] for source in records if source["category"] == "core_demo"],
        "public_dataset_adapters": [source["id"] for source in records if source["category"] == "public_dataset"],
        "facility_connector_stubs": [source["id"] for source in records if source["category"] == "facility_connector"],
        "artifact_standards": [source["id"] for source in records if source["category"] == "artifact_standard"],
        "validation_standards": [source["id"] for source in records if source["category"] == "validation_standard"],
        "future_extensions": [source["id"] for source in records if source["category"] == "future_extension"],
        "active_sources": [source["id"] for source in records if source.get("active")],
        "counts_by_category": by_category,
        "no_real_hardware": True,
        "no_runtime_downloads": True,
        "no_external_runtime_calls": True,
        "evidence_bundle_includes_registry": True,
    }


def data_sources_registry() -> dict[str, Any]:
    sources = data_sources_list()
    return {
        "registry_version": DATA_SOURCE_REGISTRY_VERSION,
        "generated_at": _now(),
        "safety_disclosure": FEDERATED_SAFETY_DISCLOSURE,
        "sources": sources,
        "summary": data_sources_summary(sources),
    }
