from __future__ import annotations

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from ghostbeam.api.runtime import list_recorded_runs, runtime

router = APIRouter(prefix="/recorded-runs", tags=["recorded-runs"])


class RecordedRunLoadRequest(BaseModel):
    run_id: str = "sample_recorded_drifted_twin"


class RecordedRunStepRequest(BaseModel):
    run_id: str = "sample_recorded_drifted_twin"
    step: int = 0


@router.get("")
def recorded_runs():
    return {
        "data_source": "recorded_fixture",
        "disclosure": "Recorded-run fixtures are generated by Ghost Beam's synthetic JAX digital twin. No real facility data are included.",
        "runs": list_recorded_runs(),
    }


@router.post("/load")
def load_recorded_run(request: RecordedRunLoadRequest):
    try:
        return runtime.load_recorded_run(request.run_id)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@router.post("/evaluate-step")
def evaluate_recorded_step(request: RecordedRunStepRequest):
    try:
        return runtime.evaluate_recorded_step(request.run_id, request.step)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
