from __future__ import annotations

from pathlib import Path
import json
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException

from ghostbeam import __version__
from ghostbeam.artifacts.decision_record import DECISION_RECORD_SCHEMA_VERSION
from ghostbeam.api.routes_public_data import public_data_status

router = APIRouter(prefix="/platform", tags=["platform"])
BACKEND_STARTED_AT = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")


@router.get("/adapters")
def platform_adapters():
    return {
        "active_adapter_id": "simulated",
        "adapters": [
            {
                "id": "simulated",
                "name": "Simulated JAX Twin",
                "status": "active",
                "read_enabled": True,
                "write_enabled": True,
                "real_hardware": False,
                "description": "Local synthetic accelerator session backed by Ghost Beam's JAX transfer-matrix twin.",
            },
            {
                "id": "replay",
                "name": "Replay Artifact",
                "status": "available_artifact",
                "read_enabled": True,
                "write_enabled": False,
                "real_hardware": False,
                "description": "Static replay fixture for reviewing a prior synthetic drifted-twin run.",
            },
            {
                "id": "recorded_fixture",
                "name": "Recorded Run Fixture",
                "status": "available_fixture",
                "read_enabled": True,
                "write_enabled": False,
                "real_hardware": False,
                "description": "CSV/eLog trace generated by Ghost Beam's synthetic JAX twin for offline replay and gate evaluation.",
            },
            {
                "id": "public_boostr",
                "name": "BOOSTR Public Data Adapter",
                "status": "available_local_import",
                "read_enabled": True,
                "write_enabled": False,
                "real_hardware": False,
                "description": "Path-restricted local importer for BOOSTR-compatible public accelerator-control slices. No auto-download and no hardware writes.",
            },
            {
                "id": "epics_stub",
                "name": "EPICS Stub",
                "status": "available_stub",
                "read_enabled": False,
                "write_enabled": False,
                "real_hardware": False,
                "description": "Interface placeholder only. No EPICS imports, network discovery, or hardware writes.",
            },
            {
                "id": "epics_archiver_stub",
                "name": "EPICS Archiver Appliance Read-Only Stub",
                "status": "stub_disabled",
                "read_enabled": False,
                "write_enabled": False,
                "real_hardware": False,
                "description": "Disabled archived-PV retrieval boundary. No network calls, PV discovery, or writes are performed.",
            },
            {
                "id": "pyarchappl_compatible",
                "name": "pyarchappl-Compatible Retrieval Interface",
                "status": "stub_disabled",
                "read_enabled": False,
                "write_enabled": False,
                "real_hardware": False,
                "description": "Future compatibility shape for EPICS Archiver Appliance retrieval; no dependency or connection is active.",
            },
            {
                "id": "future_epics",
                "name": "Future Facility EPICS Adapter",
                "status": "planned_requires_facility_review",
                "read_enabled": False,
                "write_enabled": False,
                "real_hardware": False,
                "description": "Documented swap-in boundary for a facility-approved read-only integration.",
            },
        ],
    }


@router.get("/capabilities")
def platform_capabilities():
    return {
        "adapter_mode": "simulated",
        "real_hardware_writes_enabled": False,
        "capabilities": {
            "jax_transfer_matrix_twin": True,
            "virtual_diagnostic": True,
            "uncertainty": True,
            "ood_detection": True,
            "beam_profile_vision": True,
            "elog_memory": True,
            "policy_gate": True,
            "calibration_sim": True,
            "mission_report": True,
            "decision_record_schema": True,
            "recorded_run_ingestion": True,
            "public_data_adapters": "boostr",
            "public_data_boostr": True,
            "public_data_fermilab_bpm_ipm_manifest": True,
            "data_source_registry": True,
            "epics_stub": True,
            "epics_archiver_stub": True,
            "pyarchappl_compatible_stub": True,
            "real_epics": False,
            "ro_crate_evidence_bundle": True,
            "frictionless_validation_status": True,
            "openpmd_compatibility_manifest": True,
            "workflowhub_compatibility_manifest": True,
            "materials_project_future_context": True,
        },
        "public_data_adapters": ["boostr", "fermilab_bpm_ipm"],
        "public_data_status": public_data_status(),
        "safety_notice": "Ghost Beam MVP is local-only and simulated. Real EPICS reads/writes are disabled.",
    }


@router.get("/data-manifest")
def synthetic_data_manifest():
    path = Path(__file__).resolve().parents[2] / "data" / "synthetic_data_manifest.json"
    if not path.exists():
        raise HTTPException(status_code=404, detail="synthetic data manifest not found")
    return json.loads(path.read_text(encoding="utf-8"))


@router.get("/version")
def platform_version():
    manifest_path = Path(__file__).resolve().parents[2] / "data" / "synthetic_data_manifest.json"
    boostr_manifest_path = Path(__file__).resolve().parents[2] / "data" / "public_datasets" / "boostr_manifest.json"
    return {
        "app_name": "Ghost Beam",
        "version": __version__,
        "schema_version": DECISION_RECORD_SCHEMA_VERSION,
        "backend_started_at": BACKEND_STARTED_AT,
        "route_groups_available": [
            "health",
            "state",
            "diagnostic",
            "vision",
            "elog",
            "plan",
            "artifacts",
            "experiment",
            "platform",
            "benchmark",
            "recorded-runs",
            "public-data",
            "data-sources",
        ],
        "adapter_mode": "simulated",
        "real_hardware_writes_enabled": False,
        "synthetic_data_manifest_available": manifest_path.exists(),
        "report_persistence_enabled": True,
        "benchmark_enabled": True,
        "evidence_bundle_enabled": True,
        "replay_enabled": True,
        "recorded_run_ingestion_enabled": True,
        "public_data_adapters_enabled": True,
        "public_data_adapters": ["boostr", "fermilab_bpm_ipm"],
        "boostr_manifest_available": boostr_manifest_path.exists(),
        "data_sources_registry_enabled": True,
        "epics_archiver_stub_enabled": True,
        "standards_manifests_enabled": True,
        "safety_notice": "Local-only simulated MVP. Real EPICS reads/writes and hardware control are disabled.",
    }
